# Generated by cpp4r: do not edit by hand

add_vec_for_ <- function(x, num) {
	.Call(`_cpp4rtest_add_vec_for_`, x, num)
}

data_frame_ <- function() {
	.Call(`_cpp4rtest_data_frame_`)
}

env_get_int_ <- function(env, name) {
	.Call(`_cpp4rtest_env_get_int_`, env, name)
}

env_get_str_ <- function(env, name) {
	.Call(`_cpp4rtest_env_get_str_`, env, name)
}

env_set_ <- function(env, name, value) {
	invisible(.Call(`_cpp4rtest_env_set_`, env, name, value))
}

env_exists_ <- function(env, name) {
	.Call(`_cpp4rtest_env_exists_`, env, name)
}

global_get_ <- function(name) {
	.Call(`_cpp4rtest_global_get_`, name)
}

named_doubles_ <- function() {
	.Call(`_cpp4rtest_named_doubles_`)
}

named_integers_ <- function() {
	.Call(`_cpp4rtest_named_integers_`)
}

named_strings_ <- function() {
	.Call(`_cpp4rtest_named_strings_`)
}

named_list_ <- function() {
	.Call(`_cpp4rtest_named_list_`)
}

get_by_name_ <- function(x, name) {
	.Call(`_cpp4rtest_get_by_name_`, x, name)
}

contains_name_ <- function(x, name) {
	.Call(`_cpp4rtest_contains_name_`, x, name)
}

find_name_pos_ <- function(x, name) {
	.Call(`_cpp4rtest_find_name_pos_`, x, name)
}

my_stop_n1fmt <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_stop_n1fmt`, mystring))
}

my_stop_n2fmt <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_stop_n2fmt`, mystring, myarg))
}

my_warning_n1fmt <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_warning_n1fmt`, mystring))
}

my_warning_n2fmt <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_warning_n2fmt`, mystring, myarg))
}

my_message_n1fmt <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_message_n1fmt`, mystring))
}

my_message_n2fmt <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_message_n2fmt`, mystring, myarg))
}

my_stop <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_stop`, mystring, myarg))
}

my_stop_n1 <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_stop_n1`, mystring))
}

my_warning <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_warning`, mystring, myarg))
}

my_warning_n1 <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_warning_n1`, mystring))
}

my_message <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_message`, mystring, myarg))
}

my_message_n1 <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_message_n1`, mystring))
}

remove_altrep <- function(x) {
	.Call(`_cpp4rtest_remove_altrep`, x)
}

upper_bound <- function(x, breaks) {
	.Call(`_cpp4rtest_upper_bound`, x, breaks)
}

findInterval2 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval2`, x, breaks)
}

findInterval2_5 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval2_5`, x, breaks)
}

findInterval3 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval3`, x, breaks)
}

grow_ <- function(n) {
	.Call(`_cpp4rtest_grow_`, n)
}

grow_cplx_ <- function(n) {
	.Call(`_cpp4rtest_grow_cplx_`, n)
}

insert_ <- function(num_sxp) {
	.Call(`_cpp4rtest_insert_`, num_sxp)
}

list_of_doubles_ <- function() {
	.Call(`_cpp4rtest_list_of_doubles_`)
}

list_of_integers_ <- function() {
	.Call(`_cpp4rtest_list_of_integers_`)
}

list_of_strings_ <- function() {
	.Call(`_cpp4rtest_list_of_strings_`)
}

list_of_named_ <- function() {
	.Call(`_cpp4rtest_list_of_named_`)
}

make_complex_ <- function(real, imag) {
	.Call(`_cpp4rtest_make_complex_`, real, imag)
}

complex_real_ <- function(x) {
	.Call(`_cpp4rtest_complex_real_`, x)
}

complex_imag_ <- function(x) {
	.Call(`_cpp4rtest_complex_imag_`, x)
}

complex_modulus_ <- function(x) {
	.Call(`_cpp4rtest_complex_modulus_`, x)
}

complex_add_ <- function(x, y) {
	.Call(`_cpp4rtest_complex_add_`, x, y)
}

named_list_push_back_ <- function() {
	.Call(`_cpp4rtest_named_list_push_back_`)
}

named_list_c_style_ <- function() {
	.Call(`_cpp4rtest_named_list_c_style_`)
}

ordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_ordered_map_to_list_`, x)
}

unordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_unordered_map_to_list_`, x)
}

gibbs_cpp <- function(N, thin) {
	.Call(`_cpp4rtest_gibbs_cpp`, N, thin)
}

gibbs_cpp2 <- function(N, thin) {
	.Call(`_cpp4rtest_gibbs_cpp2`, N, thin)
}

row_sums <- function(x) {
	.Call(`_cpp4rtest_row_sums`, x)
}

mat_mat_copy_dimnames <- function(x) {
	.Call(`_cpp4rtest_mat_mat_copy_dimnames`, x)
}

mat_sexp_copy_dimnames <- function(x) {
	.Call(`_cpp4rtest_mat_sexp_copy_dimnames`, x)
}

mat_mat_create_dimnames <- function() {
	.Call(`_cpp4rtest_mat_mat_create_dimnames`)
}

col_sums <- function(x) {
	.Call(`_cpp4rtest_col_sums`, x)
}

matrix_add <- function(x, y) {
	.Call(`_cpp4rtest_matrix_add`, x, y)
}

matrix_add_coerce_test <- function(x, y) {
	.Call(`_cpp4rtest_matrix_add_coerce_test`, x, y)
}

matrix_mixed_add <- function(int_mat, dbl_mat) {
	.Call(`_cpp4rtest_matrix_mixed_add`, int_mat, dbl_mat)
}

protect_one_rapi_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_rapi_`, x, n))
}

protect_one_sexp_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_sexp_`, x, n))
}

protect_one_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_`, x, n))
}

protect_one_preserve_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_preserve_`, x, n))
}

protect_many_rapi_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_rapi_`, n))
}

protect_many_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_`, n))
}

protect_many_sexp_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_sexp_`, n))
}

protect_many_preserve_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_preserve_`, n))
}

release_ <- function(n) {
	invisible(.Call(`_cpp4rtest_release_`, n))
}

notroxcpp1_ <- function(x) {
	.Call(`_cpp4rtest_notroxcpp1_`, x)
}

#' @title Roxygenise C++ function II
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 2.0 to a double.
#' @export
#' @examples roxcpp2(1.0)
roxcpp2 <- function(x) {
	.Call(`_cpp4rtest_roxcpp2`, x)
}

#' @title Roxygenise C++ function III
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 3.0 to a double.
#' @export
#' @examples roxcpp3(1.0)
roxcpp3 <- function(x) {
	.Call(`_cpp4rtest_roxcpp3`, x)
}

#' @title Roxygenise C++ function IV
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 4.0 to a double.
#' @export
#' @examples roxcpp4(1.0)
roxcpp4 <- function(x) {
	.Call(`_cpp4rtest_roxcpp4`, x)
}

#' @title Roxygenise C++ function V
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 5.0 to a double.
#' @export
#' @examples roxcpp5(1.0)
roxcpp5 <- function(x) {
	.Call(`_cpp4rtest_roxcpp5`, x)
}

notroxcpp6_ <- function(x) {
	.Call(`_cpp4rtest_notroxcpp6_`, x)
}

#' @title Roxygenise C++ function VII
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 7.0 to a double.
#' @export
#' @examples
#' my_fun <- function(x) {
#'   roxcpp7(x)
#' }
#' @seealso \code{\link{roxcpp3}}
roxcpp7 <- function(x) {
	.Call(`_cpp4rtest_roxcpp7`, x)
}

safe_ <- function(x_sxp) {
	.Call(`_cpp4rtest_safe_`, x_sxp)
}

grow_strings_ <- function(n, seed) {
	.Call(`_cpp4rtest_grow_strings_`, n, seed)
}

grow_strings_manual_ <- function(n, seed) {
	.Call(`_cpp4rtest_grow_strings_manual_`, n, seed)
}

assign_ <- function(n, seed) {
	.Call(`_cpp4rtest_assign_`, n, seed)
}

sum_dbl_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_for_`, x)
}

sum_dbl_for2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_for2_`, x_sxp)
}

sum_dbl_for3_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_for3_`, x_sxp)
}

sum_dbl_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_foreach_`, x)
}

sum_dbl_foreach2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_foreach2_`, x_sxp)
}

sum_dbl_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_accumulate_`, x)
}

sum_dbl_accumulate2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_accumulate2_`, x_sxp)
}

sum_cplx_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_for_`, x)
}

sum_cplx_for_2_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_for_2_`, x)
}

sum_cplx_for_3_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_3_`, x_sxp)
}

sum_cplx_for_4_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_4_`, x_sxp)
}

sum_cplx_for_5_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_5_`, x_sxp)
}

sum_cplx_for_6_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_6_`, x_sxp)
}

sum_cplx_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_foreach_`, x)
}

sum_cplx_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_accumulate_`, x)
}

sum_cplx_for2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for2_`, x_sxp)
}

sum_int_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_for_`, x)
}

sum_int_for2_ <- function(x_) {
	.Call(`_cpp4rtest_sum_int_for2_`, x_)
}

sum_int_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_foreach_`, x)
}

sum_int_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_accumulate_`, x)
}

nullable_extptr_1 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_1`)
}

nullable_extptr_2 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_2`)
}

add_int_vec_ <- function(x, value) {
	.Call(`_cpp4rtest_add_int_vec_`, x, value)
}

as_integers_ <- function(x) {
	.Call(`_cpp4rtest_as_integers_`, x)
}

negate_logical_ <- function(x) {
	.Call(`_cpp4rtest_negate_logical_`, x)
}

logical_to_int_ <- function(x) {
	.Call(`_cpp4rtest_logical_to_int_`, x)
}

logical_to_dbl_ <- function(x) {
	.Call(`_cpp4rtest_logical_to_dbl_`, x)
}

iterator_sum_ <- function(x) {
	.Call(`_cpp4rtest_iterator_sum_`, x)
}

iterator_sum_int_ <- function(x) {
	.Call(`_cpp4rtest_iterator_sum_int_`, x)
}

iterator_find_ <- function(x, value) {
	.Call(`_cpp4rtest_iterator_find_`, x, value)
}

iterator_count_ <- function(x, value) {
	.Call(`_cpp4rtest_iterator_count_`, x, value)
}

iterator_min_ <- function(x) {
	.Call(`_cpp4rtest_iterator_min_`, x)
}

iterator_max_ <- function(x) {
	.Call(`_cpp4rtest_iterator_max_`, x)
}

iterator_double_values_ <- function(x) {
	.Call(`_cpp4rtest_iterator_double_values_`, x)
}

reverse_vector_ <- function(x) {
	.Call(`_cpp4rtest_reverse_vector_`, x)
}

iterator_at_ <- function(x, index) {
	.Call(`_cpp4rtest_iterator_at_`, x, index)
}

iterator_distance_ <- function(x) {
	.Call(`_cpp4rtest_iterator_distance_`, x)
}

raw_copy_ <- function(x) {
	.Call(`_cpp4rtest_raw_copy_`, x)
}

raw_xor_ <- function(x, mask) {
	.Call(`_cpp4rtest_raw_xor_`, x, mask)
}

test_destruction_inner <- function() {
	invisible(.Call(`_cpp4rtest_test_destruction_inner`))
}

test_destruction_outer <- function() {
	invisible(.Call(`_cpp4rtest_test_destruction_outer`))
}

push_and_truncate_ <- function(size_sexp) {
	.Call(`_cpp4rtest_push_and_truncate_`, size_sexp)
}
