# Generated by cpp4r: do not edit by hand

#' @title Add functions
#' @rdname testing-add
#' @keywords internal
cpp4r_add_vec_for_ <- function(x, num) {
	num <- as.numeric(num)
	.Call(`_cpp4rtest_cpp4r_add_vec_for_`, x, num)
}

#' @title Data frame functions
#' @rdname testing-data-frame
#' @keywords internal
data_frame_ <- function() {
	.Call(`_cpp4rtest_data_frame_`)
}

my_stop_n1fmt <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_stop_n1fmt`, mystring))
}

my_stop_n2fmt <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.character(myarg)
	invisible(.Call(`_cpp4rtest_my_stop_n2fmt`, mystring, myarg))
}

my_warning_n1fmt <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_warning_n1fmt`, mystring))
}

my_warning_n2fmt <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.character(myarg)
	invisible(.Call(`_cpp4rtest_my_warning_n2fmt`, mystring, myarg))
}

my_message_n1fmt <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_message_n1fmt`, mystring))
}

my_message_n2fmt <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.character(myarg)
	invisible(.Call(`_cpp4rtest_my_message_n2fmt`, mystring, myarg))
}

my_stop <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.integer(myarg)
	invisible(.Call(`_cpp4rtest_my_stop`, mystring, myarg))
}

my_stop_n1 <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_stop_n1`, mystring))
}

my_warning <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.character(myarg)
	invisible(.Call(`_cpp4rtest_my_warning`, mystring, myarg))
}

my_warning_n1 <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_warning_n1`, mystring))
}

my_message <- function(mystring, myarg) {
	mystring <- as.character(mystring)
	myarg <- as.character(myarg)
	invisible(.Call(`_cpp4rtest_my_message`, mystring, myarg))
}

my_message_n1 <- function(mystring) {
	mystring <- as.character(mystring)
	invisible(.Call(`_cpp4rtest_my_message_n1`, mystring))
}

remove_altrep <- function(x) {
	.Call(`_cpp4rtest_remove_altrep`, x)
}

upper_bound <- function(x, breaks) {
	storage.mode(x) <- "double"
	storage.mode(breaks) <- "double"
	.Call(`_cpp4rtest_upper_bound`, x, breaks)
}

findInterval2 <- function(x, breaks) {
	storage.mode(x) <- "double"
	storage.mode(breaks) <- "double"
	.Call(`_cpp4rtest_findInterval2`, x, breaks)
}

findInterval2_5 <- function(x, breaks) {
	storage.mode(x) <- "double"
	storage.mode(breaks) <- "double"
	.Call(`_cpp4rtest_findInterval2_5`, x, breaks)
}

findInterval3 <- function(x, breaks) {
	storage.mode(x) <- "double"
	storage.mode(breaks) <- "double"
	.Call(`_cpp4rtest_findInterval3`, x, breaks)
}

#' @title Grow functions
#' @rdname testing-grow
#' @keywords internal
grow_ <- function(n) {
	.Call(`_cpp4rtest_grow_`, n)
}

#' @title Grow functions
#' @rdname testing-grow
#' @keywords internal
grow_cplx_ <- function(n) {
	.Call(`_cpp4rtest_grow_cplx_`, n)
}

#' @title Insert functions
#' @rdname testing-insert
#' @keywords internal
cpp4r_insert_ <- function(num_sxp) {
	.Call(`_cpp4rtest_cpp4r_insert_`, num_sxp)
}

#' @title List functions
#' @rdname testing-list
#' @keywords internal
cpp4r_named_list_push_back_ <- function() {
	.Call(`_cpp4rtest_cpp4r_named_list_push_back_`)
}

#' @title List functions
#' @rdname testing-list
#' @keywords internal
cpp4r_named_list_c_style_ <- function() {
	.Call(`_cpp4rtest_cpp4r_named_list_c_style_`)
}

#' @title List functions for cpp4r
#' @rdname testing-map
#' @keywords internal
ordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_ordered_map_to_list_`, x)
}

#' @title List functions for cpp4r
#' @rdname testing-map
#' @keywords internal
unordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_unordered_map_to_list_`, x)
}

gibbs_cpp <- function(N, thin) {
	N <- as.integer(N)
	thin <- as.integer(thin)
	.Call(`_cpp4rtest_gibbs_cpp`, N, thin)
}

gibbs_cpp2 <- function(N, thin) {
	N <- as.integer(N)
	thin <- as.integer(thin)
	.Call(`_cpp4rtest_gibbs_cpp2`, N, thin)
}

row_sums <- function(x) {
	storage.mode(x) <- "double"
	.Call(`_cpp4rtest_row_sums`, x)
}

mat_mat_copy_dimnames <- function(x) {
	storage.mode(x) <- "double"
	.Call(`_cpp4rtest_mat_mat_copy_dimnames`, x)
}

mat_sexp_copy_dimnames <- function(x) {
	storage.mode(x) <- "double"
	.Call(`_cpp4rtest_mat_sexp_copy_dimnames`, x)
}

mat_mat_create_dimnames <- function() {
	.Call(`_cpp4rtest_mat_mat_create_dimnames`)
}

col_sums <- function(x) {
	storage.mode(x) <- "double"
	.Call(`_cpp4rtest_col_sums`, x)
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_one_ <- function(x, n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_one_`, x, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_one_sexp_ <- function(x, n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_one_sexp_`, x, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_one_cpp4r_ <- function(x, n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_one_cpp4r_`, x, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_one_preserve_ <- function(x, n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_one_preserve_`, x, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_many_ <- function(n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_many_`, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_many_cpp4r_ <- function(n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_many_cpp4r_`, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_many_sexp_ <- function(n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_many_sexp_`, n))
}

#' @title Protect functions
#' @rdname testing-protect
#' @keywords internal
protect_many_preserve_ <- function(n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_protect_many_preserve_`, n))
}

#' @title Release functions
#' @rdname testing-release
#' @keywords internal
cpp4r_release_ <- function(n) {
	n <- as.integer(n)
	invisible(.Call(`_cpp4rtest_cpp4r_release_`, n))
}

notroxcpp1_ <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_notroxcpp1_`, x)
}

#' @title Roxygenise C++ function II
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 2.0 to a double.
#' @export
#' @examples roxcpp2(1.0)
roxcpp2 <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_roxcpp2`, x)
}

#' @title Roxygenise C++ function III
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 3.0 to a double.
#' @export
#' @examples roxcpp3(1.0)
roxcpp3 <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_roxcpp3`, x)
}

#' @title Roxygenise C++ function IV
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 4.0 to a double.
#' @export
#' @examples roxcpp4(1.0)
roxcpp4 <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_roxcpp4`, x)
}

#' @title Roxygenise C++ function V
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 5.0 to a double.
#' @export
#' @examples roxcpp5(1.0)
roxcpp5 <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_roxcpp5`, x)
}

notroxcpp6_ <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_notroxcpp6_`, x)
}

#' @title Roxygenise C++ function VII
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 7.0 to a double.
#' @export
#' @examples
#' my_fun <- function(x) {
#'   roxcpp7(x)
#' }
#' @seealso \code{\link{roxcpp3}}
roxcpp7 <- function(x) {
	x <- as.numeric(x)
	.Call(`_cpp4rtest_roxcpp7`, x)
}

#' @title Safe functions
#' @rdname testing-safe
#' @keywords internal
cpp4r_safe_ <- function(x_sxp) {
	.Call(`_cpp4rtest_cpp4r_safe_`, x_sxp)
}

#' @title Grow functions
#' @rdname testing-grow-strings
#' @keywords internal
grow_strings_cpp4r_ <- function(n, seed) {
	seed <- as.integer(seed)
	.Call(`_cpp4rtest_grow_strings_cpp4r_`, n, seed)
}

#' @title Grow functions
#' @rdname testing-grow-strings
#' @keywords internal
grow_strings_manual_ <- function(n, seed) {
	seed <- as.integer(seed)
	.Call(`_cpp4rtest_grow_strings_manual_`, n, seed)
}

#' @title Grow functions
#' @rdname testing-grow-strings
#' @keywords internal
assign_cpp4r_ <- function(n, seed) {
	seed <- as.integer(seed)
	.Call(`_cpp4rtest_assign_cpp4r_`, n, seed)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_for_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_for2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_for2_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_for3_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_for3_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_foreach_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_foreach2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_foreach2_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_accumulate_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_dbl_accumulate2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_accumulate2_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_for_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_2_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_for_2_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_3_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_3_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_4_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_4_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_5_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_5_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for_6_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for_6_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_foreach_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_accumulate_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_cplx_for2_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_for2_`, x_sxp)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_int_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_for_`, x)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_int_for2_ <- function(x_) {
	.Call(`_cpp4rtest_sum_int_for2_`, x_)
}

#' @title Sum functions
#' @rdname testing-sum
#' @keywords internal
sum_int_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_foreach_`, x)
}

#' @title Sum functionscpp4r
#' @rdname testing-sum
#' @keywords internal
sum_int_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_accumulate_`, x)
}

nullable_extptr_1 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_1`)
}

nullable_extptr_2 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_2`)
}

test_destruction_inner <- function() {
	invisible(.Call(`_cpp4rtest_test_destruction_inner`))
}

test_destruction_outer <- function() {
	invisible(.Call(`_cpp4rtest_test_destruction_outer`))
}

#' @title Push functions
#' @rdname testing-push
#' @keywords internal
cpp4r_push_and_truncate_ <- function(size_sexp) {
	.Call(`_cpp4rtest_cpp4r_push_and_truncate_`, size_sexp)
}
