# Generated by cpp4r: do not edit by hand

#' @title Sum Doubles on 'C++' Side
#' @description Test suite
#' @param x vector of doubles (R)
#' @param num single double (C++)
#' @export
add_vec_for_ <- function(x, num) {
	.Call(`_cpp4rtest_add_vec_for_`, x, num)
}

#' @title Create a Data Frame on 'C++' Side (SEXP in, SEXP out)
#' @description Test suite
#' @export
data_frame_ <- function() {
	.Call(`_cpp4rtest_data_frame_`)
}

#' @title Get Integer from Environment on 'C++' Side
#' @description Test suite
#' @param env R environment to query
#' @param name name of the variable to get
#' @export
env_get_int_ <- function(env, name) {
	.Call(`_cpp4rtest_env_get_int_`, env, name)
}

#' @title Get String from Environment on 'C++' Side
#' @description Test suite
#' @param env R environment to query
#' @param name name of the variable to get
#' @export
env_get_str_ <- function(env, name) {
	.Call(`_cpp4rtest_env_get_str_`, env, name)
}

#' @title Set Integer in Environment on 'C++' Side
#' @description Test suite
#' @param env R environment to modify
#' @param name name of the variable to set
#' @param value integer value to set
#' @export
env_set_ <- function(env, name, value) {
	invisible(.Call(`_cpp4rtest_env_set_`, env, name, value))
}

#' @title Check if Variable Exists in Environment on 'C++' Side
#' @description Test suite
#' @param env R environment to query
#' @param name name of the variable to check
#' @export
env_exists_ <- function(env, name) {
	.Call(`_cpp4rtest_env_exists_`, env, name)
}

#' @title Get Variable from Global Environment on 'C++' Side
#' @description Test suite
#' @param name name of the variable to get
#' @export
global_get_ <- function(name) {
	.Call(`_cpp4rtest_global_get_`, name)
}

#' @title Create Named Doubles on 'C++' Side
#' @description Test suite
#' @export
named_doubles_ <- function() {
	.Call(`_cpp4rtest_named_doubles_`)
}

#' @title Create Named Integers on 'C++' Side
#' @description Test suite
#' @export
named_integers_ <- function() {
	.Call(`_cpp4rtest_named_integers_`)
}

#' @title Create Named Strings on 'C++' Side
#' @description Test suite
#' @export
named_strings_ <- function() {
	.Call(`_cpp4rtest_named_strings_`)
}

#' @title Create Named List on 'C++' Side
#' @description Test suite
#' @export
named_list_ <- function() {
	.Call(`_cpp4rtest_named_list_`)
}

#' @title Get Value by Name from Named Vector on 'C++' Side
#' @description Test suite
#' @param x named vector to query
#' @param name name of the element to get
#' @export
get_by_name_ <- function(x, name) {
	.Call(`_cpp4rtest_get_by_name_`, x, name)
}

#' @title Check if Named Vector Contains Name on 'C++' Side
#' @description Test suite
#' @param x named vector to query
#' @param name name of the element to check
#' @export
contains_name_ <- function(x, name) {
	.Call(`_cpp4rtest_contains_name_`, x, name)
}

#' @title Find Position of Name in Named Vector on 'C++' Side
#' @description Test suite
#' @param x named vector to query
#' @param name name of the element to find
#' @export
find_name_pos_ <- function(x, name) {
	.Call(`_cpp4rtest_find_name_pos_`, x, name)
}

#' @title Errors
#' @description Test suite
#' @param mystring string to include in the error/warning/message
#' @export
my_stop_n1_ <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_stop_n1_`, mystring))
}

#' @title Errors with Two Arguments
#' @description Test suite
#' @param mystring string to include in the error
#' @param myarg additional string to include in the error
#' @export
my_stop_n2_ <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_stop_n2_`, mystring, myarg))
}

#' @title Warnings with One Argument
#' @description Test suite
#' @param mystring string to include in the warning
#' @export
my_warning_n1_ <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_warning_n1_`, mystring))
}

#' @title Warnings with Two Arguments
#' @description Test suite
#' @param mystring string to include in the warning
#' @param myarg additional string to include in the warning
#' @export
my_warning_n2_ <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_warning_n2_`, mystring, myarg))
}

#' @title Messages with One Argument
#' @description Test suite
#' @param mystring string to include in the message
#' @export
my_message_n1_ <- function(mystring) {
	invisible(.Call(`_cpp4rtest_my_message_n1_`, mystring))
}

#' @title Messages with Two Arguments
#' @description Test suite
#' @param mystring string to include in the message
#' @param myarg additional string to include in the message
#' @export
my_message_n2_ <- function(mystring, myarg) {
	invisible(.Call(`_cpp4rtest_my_message_n2_`, mystring, myarg))
}

#' @title Test Nullable External Pointer on 'C++' Side (nullptr)
#' @description Test suite
#' @export
nullable_extptr_1 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_1`)
}

#' @title Test Nullable External Pointer on 'C++' Side (R_NilValue)
#' @description Test suite
#' @export
nullable_extptr_2 <- function() {
	.Call(`_cpp4rtest_nullable_extptr_2`)
}

#' @title Remove ALTREP from Vector on 'C++' Side
#' @description Test suite
#' @param x vector to process
#' @export
remove_altrep <- function(x) {
	.Call(`_cpp4rtest_remove_altrep`, x)
}

#' @title Find Interval for a Single Value on 'C++' Side (typed in, double out)
#' @description Test suite
#' @param x single value to find interval for
#' @param breaks vector of break points
#' @export
upper_bound <- function(x, breaks) {
	.Call(`_cpp4rtest_upper_bound`, x, breaks)
}

#' @title Find Interval for Multiple Values on 'C++' Side
#' @description Test suite
#' @param x vector of values to find intervals for
#' @param breaks vector of break points
#' @export
findInterval2 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval2`, x, breaks)
}

#' @title Find Interval for Multiple Values on 'C++' Side (optimized)
#' @description Test suite
#' @param x vector of values to find intervals for
#' @param breaks vector of break points
#' @export
findInterval2_5 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval2_5`, x, breaks)
}

#' @title Find Interval for Multiple Values on 'C++' Side (optimized, raw pointers)
#' @description Test suite
#' @param x vector of values to find intervals for
#' @param breaks vector of break points
#' @export
findInterval3 <- function(x, breaks) {
	.Call(`_cpp4rtest_findInterval3`, x, breaks)
}

#' @title Grow a Vector on 'C++' Side (SEXP in, SEXP out)
#' @description Test suite
#' @param n length of the vector to grow
#' @export
grow_ <- function(n) {
	.Call(`_cpp4rtest_grow_`, n)
}

#' @title Grow a Complex Vector on 'C++' Side (SEXP in, SEXP out)
#' @description Test suite
#' @param n length of the vector to grow
#' @export
grow_cplx_ <- function(n) {
	.Call(`_cpp4rtest_grow_cplx_`, n)
}

#' @title Insert Doubles
#' @description Test suite
#' @param num_sxp number of doubles to insert
#' @export
insert_ <- function(num_sxp) {
	.Call(`_cpp4rtest_insert_`, num_sxp)
}

#' @title Create List of Doubles
#' @description Test suite
#' @export
list_of_doubles_ <- function() {
	.Call(`_cpp4rtest_list_of_doubles_`)
}

#' @title Create List of Integers
#' @description Test suite
#' @export
list_of_integers_ <- function() {
	.Call(`_cpp4rtest_list_of_integers_`)
}

#' @title Create List of Strings
#' @description Test suite
#' @export
list_of_strings_ <- function() {
	.Call(`_cpp4rtest_list_of_strings_`)
}

#' @title Create Named List
#' @description Test suite
#' @export
list_of_named_ <- function() {
	.Call(`_cpp4rtest_list_of_named_`)
}

#' @title Create Complex Numbers on 'C++' Side (typed in, r_complex out)
#' @description Test suite
#' @param real vector of real parts
#' @param imag vector of imaginary parts
#' @export
make_complex_ <- function(real, imag) {
	.Call(`_cpp4rtest_make_complex_`, real, imag)
}

#' @title Extract Real Part of Complex Numbers on 'C++' Side (typed in, r_complex out)
#' @description Test suite
#' @param x vector of complex numbers
#' @export
complex_real_ <- function(x) {
	.Call(`_cpp4rtest_complex_real_`, x)
}

#' @title Extract Imaginary Part of Complex Numbers on 'C++' Side (typed in, r_complex out)
#' @description Test suite
#' @param x vector of complex numbers
#' @export
complex_imag_ <- function(x) {
	.Call(`_cpp4rtest_complex_imag_`, x)
}

#' @title Compute Modulus of Complex Numbers on 'C++' Side (typed in, r_complex out)
#' @description Test suite
#' @param x vector of complex numbers
#' @export
complex_modulus_ <- function(x) {
	.Call(`_cpp4rtest_complex_modulus_`, x)
}

#' @title Add Complex Vectors on 'C++' Side (typed in, complexes out)
#' @description Test suite
#' @param x vector of complex numbers
#' @param y vector of complex numbers
#' @export
complex_add_ <- function(x, y) {
	.Call(`_cpp4rtest_complex_add_`, x, y)
}

#' @title Create Named List by Pushing Back Elements
#' @description Test suite
#' @export
named_list_push_back_ <- function() {
	.Call(`_cpp4rtest_named_list_push_back_`)
}

#' @title Create Named List by C-Style Assignment
#' @description Test suite
#' @export
named_list_c_style_ <- function() {
	.Call(`_cpp4rtest_named_list_c_style_`)
}

#' @title Convert Ordered Map to List
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
ordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_ordered_map_to_list_`, x)
}

#' @title Convert Unordered Map to List
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
unordered_map_to_list_ <- function(x) {
	.Call(`_cpp4rtest_unordered_map_to_list_`, x)
}

#' @title Gibbs Sampler in C++
#' @description Test suite
#' @param N number of iterations
#' @param thin thinning parameter
#' @export
gibbs_cpp_ <- function(N, thin) {
	.Call(`_cpp4rtest_gibbs_cpp_`, N, thin)
}

#' @title Gibbs Sampler in C++ (Alternative)
#' @description Test suite
#' @param N number of iterations
#' @param thin thinning parameter
#' @export
gibbs_cpp2_ <- function(N, thin) {
	.Call(`_cpp4rtest_gibbs_cpp2_`, N, thin)
}

#' @title Convert Raw Vector to Raw Vector (Identity)
#' @description Test suite
#' @param x vector of raw bytes (R)
#' @export
row_sums_ <- function(x) {
	.Call(`_cpp4rtest_row_sums_`, x)
}

#' @title Copy Matrix with Dimnames
#' @description Test suite
#' @param x matrix to copy
#' @export
mat_mat_copy_dimnames_ <- function(x) {
	.Call(`_cpp4rtest_mat_mat_copy_dimnames_`, x)
}

#' @title Copy Matrix with Dimnames (SEXP)
#' @description Test suite
#' @param x matrix to copy
#' @export
mat_sexp_copy_dimnames_ <- function(x) {
	.Call(`_cpp4rtest_mat_sexp_copy_dimnames_`, x)
}

#' @title Create Matrix with Dimnames
#' @description Test suite
#' @export
mat_mat_create_dimnames_ <- function() {
	.Call(`_cpp4rtest_mat_mat_create_dimnames_`)
}

#' @title Compute Column Sums
#' @description Test suite
#' @param x matrix of doubles (R)
#' @export
col_sums_ <- function(x) {
	.Call(`_cpp4rtest_col_sums_`, x)
}

#' @title Add Two Matrices (with Coercion)
#' @description Test suite
#' @param x first matrix (R)
#' @param y second matrix (R)
#' @export
matrix_add_ <- function(x, y) {
	.Call(`_cpp4rtest_matrix_add_`, x, y)
}

#' @title Add Two Matrices (with Integer Coercion)
#' @description Test suite
#' @param x first matrix (R)
#' @param y second matrix (R)
#' @export
matrix_add_coerce_test_ <- function(x, y) {
	.Call(`_cpp4rtest_matrix_add_coerce_test_`, x, y)
}

#' @title Add Integer Matrix and Double Matrix
#' @description Test suite
#' @param int_mat integer matrix (R)
#' @param dbl_mat double matrix (R)
#' @export
matrix_mixed_add_ <- function(int_mat, dbl_mat) {
	.Call(`_cpp4rtest_matrix_mixed_add_`, int_mat, dbl_mat)
}

#' @title Get Size of Pairlist (int output)
#' @description Test suite
#' @param pl pairlist to query
#' @export
pairlist_size_ <- function(pl) {
	.Call(`_cpp4rtest_pairlist_size_`, pl)
}

#' @title Convert Pairlist to List (list output)
#' @description Test suite
#' @param pl pairlist to convert
#' @export
pairlist_to_list_ <- function(pl) {
	.Call(`_cpp4rtest_pairlist_to_list_`, pl)
}

#' @title Reject Vector Input for Pairlist
#' @description Test suite
#' @export
pairlist_rejects_vec_ <- function() {
	invisible(.Call(`_cpp4rtest_pairlist_rejects_vec_`))
}

#' @title Protect One Object Using R API
#' @description Test suite
#' @param x object to protect
#' @param n number of times to protect
#' @export
protect_one_rapi_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_rapi_`, x, n))
}

#' @title Protect One Object Using cpp4r Store
#' @description Test suite
#' @param x object to protect
#' @param n number of times to protect
#' @export
protect_one_sexp_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_sexp_`, x, n))
}

#' @title Protect One Object Using cpp4r Store
#' @description Test suite
#' @param x object to protect
#' @param n number of times to protect
#' @export
protect_one_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_`, x, n))
}

#' @title Protect One Object Using R_PreserveObject
#' @description Test suite
#' @param x object to protect
#' @param n number of times to protect
#' @export
protect_one_preserve_ <- function(x, n) {
	invisible(.Call(`_cpp4rtest_protect_one_preserve_`, x, n))
}

#' @title Protect Many Objects Using R API
#' @description Test suite
#' @param n number of objects to protect
#' @export
protect_many_rapi_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_rapi_`, n))
}

#' @title Protect Many Objects Using cpp4r Store
#' @description Test suite
#' @param n number of objects to protect
#' @export
protect_many_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_`, n))
}

#' @title Protect Many Objects Using cpp4r SEXP
#' @description Test suite
#' @param n number of objects to protect
#' @export
protect_many_sexp_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_sexp_`, n))
}

#' @title Protect Many Objects Using R_PreserveObject
#' @description Test suite
#' @param n number of objects to protect
#' @export
protect_many_preserve_ <- function(n) {
	invisible(.Call(`_cpp4rtest_protect_many_preserve_`, n))
}

#' @title Release
#' @description Test suite
#' @param n number of objects to protect and release
#' @export
release_ <- function(n) {
	invisible(.Call(`_cpp4rtest_release_`, n))
}

#' @title Safe Execution of R Code
#' @description Test suite
#' @param x_sxp object to process
#' @export
safe_ <- function(x_sxp) {
	.Call(`_cpp4rtest_safe_`, x_sxp)
}

#' @title Initialize a List of SEXP Objects
#' @description Test suite
#' @export
sexp_list_init_ <- function() {
	.Call(`_cpp4rtest_sexp_list_init_`)
}

#' @title Initialize a Scalar List of SEXP Objects
#' @description Test suite
#' @export
sexp_scalar_list_init_ <- function() {
	.Call(`_cpp4rtest_sexp_scalar_list_init_`)
}

#' @title Grow Strings
#' @description Test suite
#' @param n number of strings to grow
#' @param seed seed for random string generation
#' @export
grow_strings_ <- function(n, seed) {
	.Call(`_cpp4rtest_grow_strings_`, n, seed)
}

#' @title Grow Strings Manually
#' @description Test suite
#' @param n number of strings to grow
#' @param seed seed for random string generation
#' @export
grow_strings_manual_ <- function(n, seed) {
	.Call(`_cpp4rtest_grow_strings_manual_`, n, seed)
}

#' @title Assign Strings
#' @description Test suite
#' @param n number of strings to assign
#' @param seed seed for random string generation
#' @export
assign_ <- function(n, seed) {
	.Call(`_cpp4rtest_assign_`, n, seed)
}

#' @title Sum Double Numbers on 'C++' Side (typed in, double out)
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
sum_dbl_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_for_`, x)
}

#' @title Sum Double Numbers on 'C++' Side (SEXP in, double out)
#' @description Test suite
#' @param x_sxp vector of double numbers (R)
#' @export
sum_dbl_sexp_for_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_sexp_for_`, x_sxp)
}

#' @title Sum Double Numbers on 'C++' Side (SEXP in no protect, double out)
#' @description Test suite
#' @param x_sxp vector of double numbers (R)
#' @export
sum_dbl_sexp_writable_for_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_sexp_writable_for_`, x_sxp)
}

#' @title Sum Double Numbers on 'C++' Side (typed in, double out)
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
sum_dbl_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_foreach_`, x)
}

#' @title Sum Double Numbers on 'C++' Side (SEXP in, double out)
#' @description Test suite
#' @param x_sxp vector of double numbers (R)
#' @export
sum_dbl_sexp_foreach_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_sexp_foreach_`, x_sxp)
}

#' @title Sum Double Numbers on 'C++' Side (typed in, double out)
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
sum_dbl_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_dbl_accumulate_`, x)
}

#' @title Sum Double Numbers on 'C++' Side (SEXP in, double out)
#' @description Test suite
#' @param x_sxp vector of double numbers (R)
#' @export
sum_dbl_sexp_accumulate_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_dbl_sexp_accumulate_`, x_sxp)
}

#' @title Sum Complex Numbers on 'C++' Side (typed in, r_complex out)
#' @description Test suite
#' @param x vector of complex numbers (R)
#' @export
sum_cplx_r_complex_out_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_r_complex_out_`, x)
}

#' @title Sum Complex Numbers on 'C++' Side (typed in, complexes out)
#' @description Test suite
#' @param x vector of complex numbers (R)
#' @export
sum_cplx_complexes_out_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_complexes_out_`, x)
}

#' @title Sum Complex Numbers on 'C++' Side (typed in re-wrapped, std out)
#' @description Test suite
#' @param x_sxp vector of complex numbers (R)
#' @export
sum_cplx_typed_std_out_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_typed_std_out_`, x_sxp)
}

#' @title Sum Complex Numbers on 'C++' Side (SEXP in no protect, std out)
#' @description Test suite
#' @param x_sxp vector of complex numbers (R)
#' @export
sum_cplx_sexp_std_out_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_sexp_std_out_`, x_sxp)
}

#' @title Sum Complex Numbers on 'C++' Side (SEXP in, SEXP out)
#' @description Test suite
#' @param x_sxp vector of complex numbers (R)
#' @export
sum_cplx_sexp_sexp_out_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_sexp_sexp_out_`, x_sxp)
}

#' @title Sum Complex Numbers on 'C++' Side (SEXP in, complexes out)
#' @description Test suite
#' @param x_sxp vector of complex numbers (R)
#' @export
sum_cplx_sexp_complexes_out_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_sexp_complexes_out_`, x_sxp)
}

#' @title Sum Complex Numbers on 'C++' Side (foreach, std out)
#' @description Test suite
#' @param x vector of complex numbers (R)
#' @export
sum_cplx_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_foreach_`, x)
}

#' @title Sum Complex Numbers on 'C++' Side (accumulate, std out)
#' @description Test suite
#' @param x vector of complex numbers (R)
#' @export
sum_cplx_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_cplx_accumulate_`, x)
}

#' @title Sum Complex Numbers on 'C++' Side (SEXP in with protect, std out)
#' @description Test suite
#' @param x_sxp vector of complex numbers (R)
#' @export
sum_cplx_sexp_protect_std_out_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_cplx_sexp_protect_std_out_`, x_sxp)
}

#' @title Sum Integer Numbers on 'C++' Side (typed in, double out, for loop)
#' @description Test suite
#' @param x vector of integer numbers (R)
#' @export
sum_int_for_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_for_`, x)
}

#' @title Sum Integer Numbers on 'C++' Side (SEXP in no protect, double out, for loop)
#' @description Test suite
#' @param x_sxp vector of integer numbers (R)
#' @export
sum_int_sexp_for_ <- function(x_sxp) {
	.Call(`_cpp4rtest_sum_int_sexp_for_`, x_sxp)
}

#' @title Sum Integer Numbers on 'C++' Side (typed in, double out, foreach)
#' @description Test suite
#' @param x vector of integer numbers (R)
#' @export
sum_int_foreach_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_foreach_`, x)
}

#' @title Sum Integer Numbers on 'C++' Side (typed in, double out, accumulate)
#' @description Test suite
#' @param x vector of integer numbers (R)
#' @export
sum_int_accumulate_ <- function(x) {
	.Call(`_cpp4rtest_sum_int_accumulate_`, x)
}

#' @title Add Integer Value to Integer Vector
#' @description Test suite
#' @param x vector of integer numbers (R)
#' @param value integer value to add
#' @export
add_int_vec_ <- function(x, value) {
	.Call(`_cpp4rtest_add_int_vec_`, x, value)
}

#' @title Convert Double Vector to Integer Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
as_integers_ <- function(x) {
	.Call(`_cpp4rtest_as_integers_`, x)
}

#' @title Convert Logical Vector to Integer Vector
#' @description Test suite
#' @param x vector of logical values (R)
#' @export
negate_logical_ <- function(x) {
	.Call(`_cpp4rtest_negate_logical_`, x)
}

#' @title Convert Logical Vector to Integer Vector
#' @description Test suite
#' @param x vector of logical values (R)
#' @export
logical_to_int_ <- function(x) {
	.Call(`_cpp4rtest_logical_to_int_`, x)
}

#' @title Convert Logical Vector to Double Vector
#' @description Test suite
#' @param x vector of logical values (R)
#' @export
logical_to_dbl_ <- function(x) {
	.Call(`_cpp4rtest_logical_to_dbl_`, x)
}

#' @title Sum Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
iterator_sum_ <- function(x) {
	.Call(`_cpp4rtest_iterator_sum_`, x)
}

#' @title Sum Integer Vector
#' @description Test suite
#' @param x vector of integer numbers (R)
#' @export
iterator_sum_int_ <- function(x) {
	.Call(`_cpp4rtest_iterator_sum_int_`, x)
}

#' @title Find Value in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @param value double value to find
#' @export
iterator_find_ <- function(x, value) {
	.Call(`_cpp4rtest_iterator_find_`, x, value)
}

#' @title Count Value in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @param value double value to count
#' @export
iterator_count_ <- function(x, value) {
	.Call(`_cpp4rtest_iterator_count_`, x, value)
}

#' @title Find Minimum Value in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
iterator_min_ <- function(x) {
	.Call(`_cpp4rtest_iterator_min_`, x)
}

#' @title Find Maximum Value in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
iterator_max_ <- function(x) {
	.Call(`_cpp4rtest_iterator_max_`, x)
}

#' @title Double Values in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
iterator_double_values_ <- function(x) {
	.Call(`_cpp4rtest_iterator_double_values_`, x)
}

#' @title Reverse Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
reverse_vector_ <- function(x) {
	.Call(`_cpp4rtest_reverse_vector_`, x)
}

#' @title Access Element in Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @param index index of the element to access (1-based)
#' @export
iterator_at_ <- function(x, index) {
	.Call(`_cpp4rtest_iterator_at_`, x, index)
}

#' @title Get Distance of Double Vector
#' @description Test suite
#' @param x vector of double numbers (R)
#' @export
iterator_distance_ <- function(x) {
	.Call(`_cpp4rtest_iterator_distance_`, x)
}

#' @title Copy Raw Vector
#' @description Test suite
#' @param x vector of raw bytes (R)
#' @export
raw_copy_ <- function(x) {
	.Call(`_cpp4rtest_raw_copy_`, x)
}

#' @title XOR Raw Vector with Mask
#' @description Test suite
#' @param x vector of raw bytes (R)
#' @param mask single byte mask (R)
#' @export
raw_xor_ <- function(x, mask) {
	.Call(`_cpp4rtest_raw_xor_`, x, mask)
}

#' @title Push and Truncate Doubles
#' @description Test suite
#' @param size_sexp initial size of the vector to grow and truncate
#' @export
push_and_truncate_ <- function(size_sexp) {
	.Call(`_cpp4rtest_push_and_truncate_`, size_sexp)
}

#' @title Weak Reference Helpers
#' @description Test suite
#' @param key key for weak reference
#' @param val value for weak reference
#' @export
weak_ref_make_alive_ <- function(key, val) {
	.Call(`_cpp4rtest_weak_ref_make_alive_`, key, val)
}

#' @title Weak Reference Value
#' @description Test suite
#' @param key key for weak reference
#' @param val value for weak reference
#' @export
weak_ref_value_ <- function(key, val) {
	.Call(`_cpp4rtest_weak_ref_value_`, key, val)
}

#' @title Weak Reference Type
#' @description Test suite
#' @param key key for weak reference
#' @param val value for weak reference
#' @export
weak_ref_typeof_ <- function(key, val) {
	.Call(`_cpp4rtest_weak_ref_typeof_`, key, val)
}

#' @title Weak Reference Nil Not Alive
#' @description Test suite
#' @export
weak_ref_nil_not_alive_ <- function() {
	.Call(`_cpp4rtest_weak_ref_nil_not_alive_`)
}

#' @title Weak Reference Rejects Vectors
#' @description Test suite
#' @export
weak_ref_rejects_vec_ <- function() {
	invisible(.Call(`_cpp4rtest_weak_ref_rejects_vec_`))
}
