# Generated by cpp4r: do not edit by hand

#' @title Plus 1 (C++)
#' @param x integer
#' @description It adds 1 to an integer value.
#' @export
#' @examples plus_one(1)
plus_one <- function(x) {
  .Call(`_cpp4rexamples_plus_one`, x)
}

#' @title Plus 2.0 (C++)
#' @param x double
#' @description It adds 2.0 to a double value.
#' @export
#' @examples plus_two(1.0)
plus_two <- function(x) {
  .Call(`_cpp4rexamples_plus_two`, x)
}

#' @title Sign of a number
#' @description Returns 1 if the number is positive, -1 if negative, and 0 if zero.
#' @param x A numeric value.
#' @return An integer indicating the sign of the number.
#' @examples
#' sign_cpp(10)
#' sign_cpp(-5)
#' sign_cpp(0)
#' @export
sign_cpp <- function(x) {
  .Call(`_cpp4rexamples_sign_cpp`, x)
}

#' @title Square Coordinates (C++)
#' @param x integer vector
#' @description It squares each element of an integer vector.
#' @examples square_coordinates(1:3)
#' @export
square_coordinates <- function(x) {
  .Call(`_cpp4rexamples_square_coordinates`, x)
}

#' @title Alternative Square Coordinates (C++)
#' @param x integer vector
#' @description It squares each element of an integer vector.
#' @examples square_coordinates_2(1:3)
#' @export
square_coordinates_2 <- function(x) {
  .Call(`_cpp4rexamples_square_coordinates_2`, x)
}
