// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// add.h
SEXP add_vec_for_(cpp4r::writable::doubles x, double num);
extern "C" SEXP _cpp4rtest_add_vec_for_(SEXP x, SEXP num) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(add_vec_for_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::writable::doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<double>>(num)));
  END_CPP4R
}
// data_frame.h
SEXP data_frame_();
extern "C" SEXP _cpp4rtest_data_frame_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(data_frame_());
  END_CPP4R
}
// env-helpers.h
int env_get_int_(environment env, std::string name);
extern "C" SEXP _cpp4rtest_env_get_int_(SEXP env, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(env_get_int_(cpp4r::as_cpp<cpp4r::decay_t<environment>>(env), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
std::string env_get_str_(environment env, std::string name);
extern "C" SEXP _cpp4rtest_env_get_str_(SEXP env, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(env_get_str_(cpp4r::as_cpp<cpp4r::decay_t<environment>>(env), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
void env_set_(environment env, std::string name, int value);
extern "C" SEXP _cpp4rtest_env_set_(SEXP env, SEXP name, SEXP value) {
  BEGIN_CPP4R
    env_set_(cpp4r::as_cpp<cpp4r::decay_t<environment>>(env), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name), cpp4r::as_cpp<cpp4r::decay_t<int>>(value));
    return R_NilValue;
  END_CPP4R
}
// env-helpers.h
bool env_exists_(environment env, std::string name);
extern "C" SEXP _cpp4rtest_env_exists_(SEXP env, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(env_exists_(cpp4r::as_cpp<cpp4r::decay_t<environment>>(env), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
SEXP global_get_(std::string name);
extern "C" SEXP _cpp4rtest_global_get_(SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(global_get_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
writable::doubles named_doubles_();
extern "C" SEXP _cpp4rtest_named_doubles_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_doubles_());
  END_CPP4R
}
// env-helpers.h
writable::integers named_integers_();
extern "C" SEXP _cpp4rtest_named_integers_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_integers_());
  END_CPP4R
}
// env-helpers.h
writable::strings named_strings_();
extern "C" SEXP _cpp4rtest_named_strings_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_strings_());
  END_CPP4R
}
// env-helpers.h
writable::list named_list_();
extern "C" SEXP _cpp4rtest_named_list_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_list_());
  END_CPP4R
}
// env-helpers.h
double get_by_name_(doubles x, std::string name);
extern "C" SEXP _cpp4rtest_get_by_name_(SEXP x, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(get_by_name_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
bool contains_name_(doubles x, std::string name);
extern "C" SEXP _cpp4rtest_contains_name_(SEXP x, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(contains_name_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// env-helpers.h
int find_name_pos_(doubles x, std::string name);
extern "C" SEXP _cpp4rtest_find_name_pos_(SEXP x, SEXP name) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(find_name_pos_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(name)));
  END_CPP4R
}
// errors.h
void my_stop_n1_(std::string mystring);
extern "C" SEXP _cpp4rtest_my_stop_n1_(SEXP mystring) {
  BEGIN_CPP4R
    my_stop_n1_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring));
    return R_NilValue;
  END_CPP4R
}
// errors.h
void my_stop_n2_(std::string mystring, std::string myarg);
extern "C" SEXP _cpp4rtest_my_stop_n2_(SEXP mystring, SEXP myarg) {
  BEGIN_CPP4R
    my_stop_n2_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(myarg));
    return R_NilValue;
  END_CPP4R
}
// errors.h
void my_warning_n1_(std::string mystring);
extern "C" SEXP _cpp4rtest_my_warning_n1_(SEXP mystring) {
  BEGIN_CPP4R
    my_warning_n1_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring));
    return R_NilValue;
  END_CPP4R
}
// errors.h
void my_warning_n2_(std::string mystring, std::string myarg);
extern "C" SEXP _cpp4rtest_my_warning_n2_(SEXP mystring, SEXP myarg) {
  BEGIN_CPP4R
    my_warning_n2_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(myarg));
    return R_NilValue;
  END_CPP4R
}
// errors.h
void my_message_n1_(std::string mystring);
extern "C" SEXP _cpp4rtest_my_message_n1_(SEXP mystring) {
  BEGIN_CPP4R
    my_message_n1_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring));
    return R_NilValue;
  END_CPP4R
}
// errors.h
void my_message_n2_(std::string mystring, std::string myarg);
extern "C" SEXP _cpp4rtest_my_message_n2_(SEXP mystring, SEXP myarg) {
  BEGIN_CPP4R
    my_message_n2_(cpp4r::as_cpp<cpp4r::decay_t<std::string>>(mystring), cpp4r::as_cpp<cpp4r::decay_t<std::string>>(myarg));
    return R_NilValue;
  END_CPP4R
}
// external-pointers.h
cpp4r::external_pointer<int> nullable_extptr_1();
extern "C" SEXP _cpp4rtest_nullable_extptr_1() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(nullable_extptr_1());
  END_CPP4R
}
// external-pointers.h
cpp4r::external_pointer<int> nullable_extptr_2();
extern "C" SEXP _cpp4rtest_nullable_extptr_2() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(nullable_extptr_2());
  END_CPP4R
}
// find-intervals.h
SEXP remove_altrep(SEXP x);
extern "C" SEXP _cpp4rtest_remove_altrep(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(remove_altrep(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x)));
  END_CPP4R
}
// find-intervals.h
double upper_bound(doubles x, doubles breaks);
extern "C" SEXP _cpp4rtest_upper_bound(SEXP x, SEXP breaks) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(upper_bound(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(breaks)));
  END_CPP4R
}
// find-intervals.h
integers findInterval2(doubles x, doubles breaks);
extern "C" SEXP _cpp4rtest_findInterval2(SEXP x, SEXP breaks) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(findInterval2(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(breaks)));
  END_CPP4R
}
// find-intervals.h
integers findInterval2_5(doubles x, doubles breaks);
extern "C" SEXP _cpp4rtest_findInterval2_5(SEXP x, SEXP breaks) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(findInterval2_5(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(breaks)));
  END_CPP4R
}
// find-intervals.h
integers findInterval3(doubles x, doubles breaks);
extern "C" SEXP _cpp4rtest_findInterval3(SEXP x, SEXP breaks) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(findInterval3(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(breaks)));
  END_CPP4R
}
// grow.h
cpp4r::writable::doubles grow_(R_xlen_t n);
extern "C" SEXP _cpp4rtest_grow_(SEXP n) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(grow_(cpp4r::as_cpp<cpp4r::decay_t<R_xlen_t>>(n)));
  END_CPP4R
}
// grow.h
cpp4r::writable::complexes grow_cplx_(R_xlen_t n);
extern "C" SEXP _cpp4rtest_grow_cplx_(SEXP n) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(grow_cplx_(cpp4r::as_cpp<cpp4r::decay_t<R_xlen_t>>(n)));
  END_CPP4R
}
// insert.h
SEXP insert_(SEXP num_sxp);
extern "C" SEXP _cpp4rtest_insert_(SEXP num_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(insert_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(num_sxp)));
  END_CPP4R
}
// list-complex-helpers.h
list_of<doubles> list_of_doubles_();
extern "C" SEXP _cpp4rtest_list_of_doubles_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(list_of_doubles_());
  END_CPP4R
}
// list-complex-helpers.h
list_of<integers> list_of_integers_();
extern "C" SEXP _cpp4rtest_list_of_integers_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(list_of_integers_());
  END_CPP4R
}
// list-complex-helpers.h
list_of<strings> list_of_strings_();
extern "C" SEXP _cpp4rtest_list_of_strings_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(list_of_strings_());
  END_CPP4R
}
// list-complex-helpers.h
writable::list list_of_named_();
extern "C" SEXP _cpp4rtest_list_of_named_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(list_of_named_());
  END_CPP4R
}
// list-complex-helpers.h
writable::complexes make_complex_(doubles real, doubles imag);
extern "C" SEXP _cpp4rtest_make_complex_(SEXP real, SEXP imag) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(make_complex_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(real), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(imag)));
  END_CPP4R
}
// list-complex-helpers.h
writable::doubles complex_real_(complexes x);
extern "C" SEXP _cpp4rtest_complex_real_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(complex_real_(cpp4r::as_cpp<cpp4r::decay_t<complexes>>(x)));
  END_CPP4R
}
// list-complex-helpers.h
writable::doubles complex_imag_(complexes x);
extern "C" SEXP _cpp4rtest_complex_imag_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(complex_imag_(cpp4r::as_cpp<cpp4r::decay_t<complexes>>(x)));
  END_CPP4R
}
// list-complex-helpers.h
writable::doubles complex_modulus_(complexes x);
extern "C" SEXP _cpp4rtest_complex_modulus_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(complex_modulus_(cpp4r::as_cpp<cpp4r::decay_t<complexes>>(x)));
  END_CPP4R
}
// list-complex-helpers.h
writable::complexes complex_add_(complexes x, complexes y);
extern "C" SEXP _cpp4rtest_complex_add_(SEXP x, SEXP y) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(complex_add_(cpp4r::as_cpp<cpp4r::decay_t<complexes>>(x), cpp4r::as_cpp<cpp4r::decay_t<complexes>>(y)));
  END_CPP4R
}
// lists.h
list named_list_push_back_();
extern "C" SEXP _cpp4rtest_named_list_push_back_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_list_push_back_());
  END_CPP4R
}
// lists.h
list named_list_c_style_();
extern "C" SEXP _cpp4rtest_named_list_c_style_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(named_list_c_style_());
  END_CPP4R
}
// map.h
SEXP ordered_map_to_list_(cpp4r::doubles x);
extern "C" SEXP _cpp4rtest_ordered_map_to_list_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(ordered_map_to_list_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(x)));
  END_CPP4R
}
// map.h
SEXP unordered_map_to_list_(cpp4r::doubles x);
extern "C" SEXP _cpp4rtest_unordered_map_to_list_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(unordered_map_to_list_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(x)));
  END_CPP4R
}
// matrix.h
SEXP gibbs_cpp_(int N, int thin);
extern "C" SEXP _cpp4rtest_gibbs_cpp_(SEXP N, SEXP thin) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(gibbs_cpp_(cpp4r::as_cpp<cpp4r::decay_t<int>>(N), cpp4r::as_cpp<cpp4r::decay_t<int>>(thin)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> gibbs_cpp2_(int N, int thin);
extern "C" SEXP _cpp4rtest_gibbs_cpp2_(SEXP N, SEXP thin) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(gibbs_cpp2_(cpp4r::as_cpp<cpp4r::decay_t<int>>(N), cpp4r::as_cpp<cpp4r::decay_t<int>>(thin)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles row_sums_(cpp4r::doubles_matrix<cpp4r::by_row> x);
extern "C" SEXP _cpp4rtest_row_sums_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(row_sums_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<cpp4r::by_row>>>(x)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> mat_mat_copy_dimnames_(cpp4r::doubles_matrix<> x);
extern "C" SEXP _cpp4rtest_mat_mat_copy_dimnames_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(mat_mat_copy_dimnames_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<>>>(x)));
  END_CPP4R
}
// matrix.h
SEXP mat_sexp_copy_dimnames_(cpp4r::doubles_matrix<> x);
extern "C" SEXP _cpp4rtest_mat_sexp_copy_dimnames_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(mat_sexp_copy_dimnames_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<>>>(x)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> mat_mat_create_dimnames_();
extern "C" SEXP _cpp4rtest_mat_mat_create_dimnames_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(mat_mat_create_dimnames_());
  END_CPP4R
}
// matrix.h
cpp4r::doubles col_sums_(cpp4r::doubles_matrix<cpp4r::by_column> x);
extern "C" SEXP _cpp4rtest_col_sums_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(col_sums_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles_matrix<cpp4r::by_column>>>(x)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> matrix_add_(const cpp4r::doubles_matrix<>& x, const cpp4r::doubles_matrix<>& y);
extern "C" SEXP _cpp4rtest_matrix_add_(SEXP x, SEXP y) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(matrix_add_(cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(x), cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(y)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> matrix_add_coerce_test_(const cpp4r::doubles_matrix<>& x, const cpp4r::doubles_matrix<>& y);
extern "C" SEXP _cpp4rtest_matrix_add_coerce_test_(SEXP x, SEXP y) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(matrix_add_coerce_test_(cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(x), cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(y)));
  END_CPP4R
}
// matrix.h
cpp4r::doubles_matrix<> matrix_mixed_add_(const cpp4r::doubles_matrix<>& int_mat, const cpp4r::doubles_matrix<>& dbl_mat);
extern "C" SEXP _cpp4rtest_matrix_mixed_add_(SEXP int_mat, SEXP dbl_mat) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(matrix_mixed_add_(cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(int_mat), cpp4r::as_cpp<cpp4r::decay_t<const cpp4r::doubles_matrix<>&>>(dbl_mat)));
  END_CPP4R
}
// pairlist_helpers.h
int pairlist_size_(SEXP pl);
extern "C" SEXP _cpp4rtest_pairlist_size_(SEXP pl) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(pairlist_size_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(pl)));
  END_CPP4R
}
// pairlist_helpers.h
list pairlist_to_list_(SEXP pl);
extern "C" SEXP _cpp4rtest_pairlist_to_list_(SEXP pl) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(pairlist_to_list_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(pl)));
  END_CPP4R
}
// pairlist_helpers.h
void pairlist_rejects_vec_();
extern "C" SEXP _cpp4rtest_pairlist_rejects_vec_() {
  BEGIN_CPP4R
    pairlist_rejects_vec_();
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_one_rapi_(SEXP x, int n);
extern "C" SEXP _cpp4rtest_protect_one_rapi_(SEXP x, SEXP n) {
  BEGIN_CPP4R
    protect_one_rapi_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_one_sexp_(SEXP x, int n);
extern "C" SEXP _cpp4rtest_protect_one_sexp_(SEXP x, SEXP n) {
  BEGIN_CPP4R
    protect_one_sexp_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_one_(SEXP x, int n);
extern "C" SEXP _cpp4rtest_protect_one_(SEXP x, SEXP n) {
  BEGIN_CPP4R
    protect_one_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_one_preserve_(SEXP x, int n);
extern "C" SEXP _cpp4rtest_protect_one_preserve_(SEXP x, SEXP n) {
  BEGIN_CPP4R
    protect_one_preserve_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_many_rapi_(int n);
extern "C" SEXP _cpp4rtest_protect_many_rapi_(SEXP n) {
  BEGIN_CPP4R
    protect_many_rapi_(cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_many_(int n);
extern "C" SEXP _cpp4rtest_protect_many_(SEXP n) {
  BEGIN_CPP4R
    protect_many_(cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_many_sexp_(int n);
extern "C" SEXP _cpp4rtest_protect_many_sexp_(SEXP n) {
  BEGIN_CPP4R
    protect_many_sexp_(cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// protect.h
void protect_many_preserve_(int n);
extern "C" SEXP _cpp4rtest_protect_many_preserve_(SEXP n) {
  BEGIN_CPP4R
    protect_many_preserve_(cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// release.h
void release_(int n);
extern "C" SEXP _cpp4rtest_release_(SEXP n) {
  BEGIN_CPP4R
    release_(cpp4r::as_cpp<cpp4r::decay_t<int>>(n));
    return R_NilValue;
  END_CPP4R
}
// safe.h
SEXP safe_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_safe_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(safe_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sexp_helpers.h
list sexp_list_init_();
extern "C" SEXP _cpp4rtest_sexp_list_init_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sexp_list_init_());
  END_CPP4R
}
// sexp_helpers.h
list sexp_scalar_list_init_();
extern "C" SEXP _cpp4rtest_sexp_scalar_list_init_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sexp_scalar_list_init_());
  END_CPP4R
}
// strings.h
cpp4r::strings grow_strings_(size_t n, int seed);
extern "C" SEXP _cpp4rtest_grow_strings_(SEXP n, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(grow_strings_(cpp4r::as_cpp<cpp4r::decay_t<size_t>>(n), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// strings.h
SEXP grow_strings_manual_(size_t n, int seed);
extern "C" SEXP _cpp4rtest_grow_strings_manual_(SEXP n, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(grow_strings_manual_(cpp4r::as_cpp<cpp4r::decay_t<size_t>>(n), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// strings.h
cpp4r::strings assign_(size_t n, int seed);
extern "C" SEXP _cpp4rtest_assign_(SEXP n, SEXP seed) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(assign_(cpp4r::as_cpp<cpp4r::decay_t<size_t>>(n), cpp4r::as_cpp<cpp4r::decay_t<int>>(seed)));
  END_CPP4R
}
// sum.h
double sum_dbl_for_(cpp4r::doubles x);
extern "C" SEXP _cpp4rtest_sum_dbl_for_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_for_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(x)));
  END_CPP4R
}
// sum.h
double sum_dbl_sexp_for_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_dbl_sexp_for_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_sexp_for_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum.h
double sum_dbl_sexp_writable_for_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_dbl_sexp_writable_for_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_sexp_writable_for_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum.h
double sum_dbl_foreach_(cpp4r::doubles x);
extern "C" SEXP _cpp4rtest_sum_dbl_foreach_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_foreach_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(x)));
  END_CPP4R
}
// sum.h
double sum_dbl_sexp_foreach_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_dbl_sexp_foreach_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_sexp_foreach_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum.h
double sum_dbl_accumulate_(cpp4r::doubles x);
extern "C" SEXP _cpp4rtest_sum_dbl_accumulate_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_accumulate_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::doubles>>(x)));
  END_CPP4R
}
// sum.h
double sum_dbl_sexp_accumulate_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_dbl_sexp_accumulate_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_dbl_sexp_accumulate_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_cplx.h
cpp4r::r_complex sum_cplx_r_complex_out_(cpp4r::complexes x);
extern "C" SEXP _cpp4rtest_sum_cplx_r_complex_out_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_r_complex_out_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::complexes>>(x)));
  END_CPP4R
}
// sum_cplx.h
cpp4r::complexes sum_cplx_complexes_out_(cpp4r::complexes x);
extern "C" SEXP _cpp4rtest_sum_cplx_complexes_out_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_complexes_out_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::complexes>>(x)));
  END_CPP4R
}
// sum_cplx.h
std::complex<double> sum_cplx_typed_std_out_(cpp4r::complexes x_sxp);
extern "C" SEXP _cpp4rtest_sum_cplx_typed_std_out_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_typed_std_out_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::complexes>>(x_sxp)));
  END_CPP4R
}
// sum_cplx.h
std::complex<double> sum_cplx_sexp_std_out_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_cplx_sexp_std_out_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_sexp_std_out_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_cplx.h
SEXP sum_cplx_sexp_sexp_out_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_cplx_sexp_sexp_out_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_sexp_sexp_out_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_cplx.h
cpp4r::complexes sum_cplx_sexp_complexes_out_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_cplx_sexp_complexes_out_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_sexp_complexes_out_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_cplx.h
std::complex<double> sum_cplx_foreach_(cpp4r::complexes x);
extern "C" SEXP _cpp4rtest_sum_cplx_foreach_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_foreach_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::complexes>>(x)));
  END_CPP4R
}
// sum_cplx.h
std::complex<double> sum_cplx_accumulate_(cpp4r::complexes x);
extern "C" SEXP _cpp4rtest_sum_cplx_accumulate_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_accumulate_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::complexes>>(x)));
  END_CPP4R
}
// sum_cplx.h
std::complex<double> sum_cplx_sexp_protect_std_out_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_cplx_sexp_protect_std_out_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_cplx_sexp_protect_std_out_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_int.h
double sum_int_for_(cpp4r::integers x);
extern "C" SEXP _cpp4rtest_sum_int_for_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_int_for_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(x)));
  END_CPP4R
}
// sum_int.h
double sum_int_sexp_for_(SEXP x_sxp);
extern "C" SEXP _cpp4rtest_sum_int_sexp_for_(SEXP x_sxp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_int_sexp_for_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(x_sxp)));
  END_CPP4R
}
// sum_int.h
double sum_int_foreach_(cpp4r::integers x);
extern "C" SEXP _cpp4rtest_sum_int_foreach_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_int_foreach_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(x)));
  END_CPP4R
}
// sum_int.h
double sum_int_accumulate_(cpp4r::integers x);
extern "C" SEXP _cpp4rtest_sum_int_accumulate_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(sum_int_accumulate_(cpp4r::as_cpp<cpp4r::decay_t<cpp4r::integers>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::integers add_int_vec_(integers x, int value);
extern "C" SEXP _cpp4rtest_add_int_vec_(SEXP x, SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(add_int_vec_(cpp4r::as_cpp<cpp4r::decay_t<integers>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(value)));
  END_CPP4R
}
// test-helpers.h
integers as_integers_(doubles x);
extern "C" SEXP _cpp4rtest_as_integers_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(as_integers_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::logicals negate_logical_(logicals x);
extern "C" SEXP _cpp4rtest_negate_logical_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(negate_logical_(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::integers logical_to_int_(logicals x);
extern "C" SEXP _cpp4rtest_logical_to_int_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(logical_to_int_(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::doubles logical_to_dbl_(logicals x);
extern "C" SEXP _cpp4rtest_logical_to_dbl_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(logical_to_dbl_(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// test-helpers.h
double iterator_sum_(doubles x);
extern "C" SEXP _cpp4rtest_iterator_sum_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_sum_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
int iterator_sum_int_(integers x);
extern "C" SEXP _cpp4rtest_iterator_sum_int_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_sum_int_(cpp4r::as_cpp<cpp4r::decay_t<integers>>(x)));
  END_CPP4R
}
// test-helpers.h
int iterator_find_(doubles x, double value);
extern "C" SEXP _cpp4rtest_iterator_find_(SEXP x, SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_find_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<double>>(value)));
  END_CPP4R
}
// test-helpers.h
int iterator_count_(doubles x, double value);
extern "C" SEXP _cpp4rtest_iterator_count_(SEXP x, SEXP value) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_count_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<double>>(value)));
  END_CPP4R
}
// test-helpers.h
double iterator_min_(doubles x);
extern "C" SEXP _cpp4rtest_iterator_min_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_min_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
double iterator_max_(doubles x);
extern "C" SEXP _cpp4rtest_iterator_max_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_max_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::doubles iterator_double_values_(doubles x);
extern "C" SEXP _cpp4rtest_iterator_double_values_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_double_values_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::doubles reverse_vector_(doubles x);
extern "C" SEXP _cpp4rtest_reverse_vector_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(reverse_vector_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
double iterator_at_(doubles x, int index);
extern "C" SEXP _cpp4rtest_iterator_at_(SEXP x, SEXP index) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_at_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x), cpp4r::as_cpp<cpp4r::decay_t<int>>(index)));
  END_CPP4R
}
// test-helpers.h
int iterator_distance_(doubles x);
extern "C" SEXP _cpp4rtest_iterator_distance_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(iterator_distance_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::raws raw_copy_(raws x);
extern "C" SEXP _cpp4rtest_raw_copy_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(raw_copy_(cpp4r::as_cpp<cpp4r::decay_t<raws>>(x)));
  END_CPP4R
}
// test-helpers.h
writable::raws raw_xor_(raws x, raws mask);
extern "C" SEXP _cpp4rtest_raw_xor_(SEXP x, SEXP mask) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(raw_xor_(cpp4r::as_cpp<cpp4r::decay_t<raws>>(x), cpp4r::as_cpp<cpp4r::decay_t<raws>>(mask)));
  END_CPP4R
}
// truncate.h
SEXP push_and_truncate_(SEXP size_sexp);
extern "C" SEXP _cpp4rtest_push_and_truncate_(SEXP size_sexp) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(push_and_truncate_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(size_sexp)));
  END_CPP4R
}
// weak_ref_helpers.h
bool weak_ref_make_alive_(SEXP key, SEXP val);
extern "C" SEXP _cpp4rtest_weak_ref_make_alive_(SEXP key, SEXP val) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(weak_ref_make_alive_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(key), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(val)));
  END_CPP4R
}
// weak_ref_helpers.h
SEXP weak_ref_value_(SEXP key, SEXP val);
extern "C" SEXP _cpp4rtest_weak_ref_value_(SEXP key, SEXP val) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(weak_ref_value_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(key), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(val)));
  END_CPP4R
}
// weak_ref_helpers.h
int weak_ref_typeof_(SEXP key, SEXP val);
extern "C" SEXP _cpp4rtest_weak_ref_typeof_(SEXP key, SEXP val) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(weak_ref_typeof_(cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(key), cpp4r::as_cpp<cpp4r::decay_t<SEXP>>(val)));
  END_CPP4R
}
// weak_ref_helpers.h
bool weak_ref_nil_not_alive_();
extern "C" SEXP _cpp4rtest_weak_ref_nil_not_alive_() {
  BEGIN_CPP4R
    return cpp4r::as_sexp(weak_ref_nil_not_alive_());
  END_CPP4R
}
// weak_ref_helpers.h
void weak_ref_rejects_vec_();
extern "C" SEXP _cpp4rtest_weak_ref_rejects_vec_() {
  BEGIN_CPP4R
    weak_ref_rejects_vec_();
    return R_NilValue;
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp4rtest_add_vec_for_", (DL_FUNC) &_cpp4rtest_add_vec_for_, 2},
    {"_cpp4rtest_data_frame_", (DL_FUNC) &_cpp4rtest_data_frame_, 0},
    {"_cpp4rtest_env_get_int_", (DL_FUNC) &_cpp4rtest_env_get_int_, 2},
    {"_cpp4rtest_env_get_str_", (DL_FUNC) &_cpp4rtest_env_get_str_, 2},
    {"_cpp4rtest_env_set_", (DL_FUNC) &_cpp4rtest_env_set_, 3},
    {"_cpp4rtest_env_exists_", (DL_FUNC) &_cpp4rtest_env_exists_, 2},
    {"_cpp4rtest_global_get_", (DL_FUNC) &_cpp4rtest_global_get_, 1},
    {"_cpp4rtest_named_doubles_", (DL_FUNC) &_cpp4rtest_named_doubles_, 0},
    {"_cpp4rtest_named_integers_", (DL_FUNC) &_cpp4rtest_named_integers_, 0},
    {"_cpp4rtest_named_strings_", (DL_FUNC) &_cpp4rtest_named_strings_, 0},
    {"_cpp4rtest_named_list_", (DL_FUNC) &_cpp4rtest_named_list_, 0},
    {"_cpp4rtest_get_by_name_", (DL_FUNC) &_cpp4rtest_get_by_name_, 2},
    {"_cpp4rtest_contains_name_", (DL_FUNC) &_cpp4rtest_contains_name_, 2},
    {"_cpp4rtest_find_name_pos_", (DL_FUNC) &_cpp4rtest_find_name_pos_, 2},
    {"_cpp4rtest_my_stop_n1_", (DL_FUNC) &_cpp4rtest_my_stop_n1_, 1},
    {"_cpp4rtest_my_stop_n2_", (DL_FUNC) &_cpp4rtest_my_stop_n2_, 2},
    {"_cpp4rtest_my_warning_n1_", (DL_FUNC) &_cpp4rtest_my_warning_n1_, 1},
    {"_cpp4rtest_my_warning_n2_", (DL_FUNC) &_cpp4rtest_my_warning_n2_, 2},
    {"_cpp4rtest_my_message_n1_", (DL_FUNC) &_cpp4rtest_my_message_n1_, 1},
    {"_cpp4rtest_my_message_n2_", (DL_FUNC) &_cpp4rtest_my_message_n2_, 2},
    {"_cpp4rtest_nullable_extptr_1", (DL_FUNC) &_cpp4rtest_nullable_extptr_1, 0},
    {"_cpp4rtest_nullable_extptr_2", (DL_FUNC) &_cpp4rtest_nullable_extptr_2, 0},
    {"_cpp4rtest_remove_altrep", (DL_FUNC) &_cpp4rtest_remove_altrep, 1},
    {"_cpp4rtest_upper_bound", (DL_FUNC) &_cpp4rtest_upper_bound, 2},
    {"_cpp4rtest_findInterval2", (DL_FUNC) &_cpp4rtest_findInterval2, 2},
    {"_cpp4rtest_findInterval2_5", (DL_FUNC) &_cpp4rtest_findInterval2_5, 2},
    {"_cpp4rtest_findInterval3", (DL_FUNC) &_cpp4rtest_findInterval3, 2},
    {"_cpp4rtest_grow_", (DL_FUNC) &_cpp4rtest_grow_, 1},
    {"_cpp4rtest_grow_cplx_", (DL_FUNC) &_cpp4rtest_grow_cplx_, 1},
    {"_cpp4rtest_insert_", (DL_FUNC) &_cpp4rtest_insert_, 1},
    {"_cpp4rtest_list_of_doubles_", (DL_FUNC) &_cpp4rtest_list_of_doubles_, 0},
    {"_cpp4rtest_list_of_integers_", (DL_FUNC) &_cpp4rtest_list_of_integers_, 0},
    {"_cpp4rtest_list_of_strings_", (DL_FUNC) &_cpp4rtest_list_of_strings_, 0},
    {"_cpp4rtest_list_of_named_", (DL_FUNC) &_cpp4rtest_list_of_named_, 0},
    {"_cpp4rtest_make_complex_", (DL_FUNC) &_cpp4rtest_make_complex_, 2},
    {"_cpp4rtest_complex_real_", (DL_FUNC) &_cpp4rtest_complex_real_, 1},
    {"_cpp4rtest_complex_imag_", (DL_FUNC) &_cpp4rtest_complex_imag_, 1},
    {"_cpp4rtest_complex_modulus_", (DL_FUNC) &_cpp4rtest_complex_modulus_, 1},
    {"_cpp4rtest_complex_add_", (DL_FUNC) &_cpp4rtest_complex_add_, 2},
    {"_cpp4rtest_named_list_push_back_", (DL_FUNC) &_cpp4rtest_named_list_push_back_, 0},
    {"_cpp4rtest_named_list_c_style_", (DL_FUNC) &_cpp4rtest_named_list_c_style_, 0},
    {"_cpp4rtest_ordered_map_to_list_", (DL_FUNC) &_cpp4rtest_ordered_map_to_list_, 1},
    {"_cpp4rtest_unordered_map_to_list_", (DL_FUNC) &_cpp4rtest_unordered_map_to_list_, 1},
    {"_cpp4rtest_gibbs_cpp_", (DL_FUNC) &_cpp4rtest_gibbs_cpp_, 2},
    {"_cpp4rtest_gibbs_cpp2_", (DL_FUNC) &_cpp4rtest_gibbs_cpp2_, 2},
    {"_cpp4rtest_row_sums_", (DL_FUNC) &_cpp4rtest_row_sums_, 1},
    {"_cpp4rtest_mat_mat_copy_dimnames_", (DL_FUNC) &_cpp4rtest_mat_mat_copy_dimnames_, 1},
    {"_cpp4rtest_mat_sexp_copy_dimnames_", (DL_FUNC) &_cpp4rtest_mat_sexp_copy_dimnames_, 1},
    {"_cpp4rtest_mat_mat_create_dimnames_", (DL_FUNC) &_cpp4rtest_mat_mat_create_dimnames_, 0},
    {"_cpp4rtest_col_sums_", (DL_FUNC) &_cpp4rtest_col_sums_, 1},
    {"_cpp4rtest_matrix_add_", (DL_FUNC) &_cpp4rtest_matrix_add_, 2},
    {"_cpp4rtest_matrix_add_coerce_test_", (DL_FUNC) &_cpp4rtest_matrix_add_coerce_test_, 2},
    {"_cpp4rtest_matrix_mixed_add_", (DL_FUNC) &_cpp4rtest_matrix_mixed_add_, 2},
    {"_cpp4rtest_pairlist_size_", (DL_FUNC) &_cpp4rtest_pairlist_size_, 1},
    {"_cpp4rtest_pairlist_to_list_", (DL_FUNC) &_cpp4rtest_pairlist_to_list_, 1},
    {"_cpp4rtest_pairlist_rejects_vec_", (DL_FUNC) &_cpp4rtest_pairlist_rejects_vec_, 0},
    {"_cpp4rtest_protect_one_rapi_", (DL_FUNC) &_cpp4rtest_protect_one_rapi_, 2},
    {"_cpp4rtest_protect_one_sexp_", (DL_FUNC) &_cpp4rtest_protect_one_sexp_, 2},
    {"_cpp4rtest_protect_one_", (DL_FUNC) &_cpp4rtest_protect_one_, 2},
    {"_cpp4rtest_protect_one_preserve_", (DL_FUNC) &_cpp4rtest_protect_one_preserve_, 2},
    {"_cpp4rtest_protect_many_rapi_", (DL_FUNC) &_cpp4rtest_protect_many_rapi_, 1},
    {"_cpp4rtest_protect_many_", (DL_FUNC) &_cpp4rtest_protect_many_, 1},
    {"_cpp4rtest_protect_many_sexp_", (DL_FUNC) &_cpp4rtest_protect_many_sexp_, 1},
    {"_cpp4rtest_protect_many_preserve_", (DL_FUNC) &_cpp4rtest_protect_many_preserve_, 1},
    {"_cpp4rtest_release_", (DL_FUNC) &_cpp4rtest_release_, 1},
    {"_cpp4rtest_safe_", (DL_FUNC) &_cpp4rtest_safe_, 1},
    {"_cpp4rtest_sexp_list_init_", (DL_FUNC) &_cpp4rtest_sexp_list_init_, 0},
    {"_cpp4rtest_sexp_scalar_list_init_", (DL_FUNC) &_cpp4rtest_sexp_scalar_list_init_, 0},
    {"_cpp4rtest_grow_strings_", (DL_FUNC) &_cpp4rtest_grow_strings_, 2},
    {"_cpp4rtest_grow_strings_manual_", (DL_FUNC) &_cpp4rtest_grow_strings_manual_, 2},
    {"_cpp4rtest_assign_", (DL_FUNC) &_cpp4rtest_assign_, 2},
    {"_cpp4rtest_sum_dbl_for_", (DL_FUNC) &_cpp4rtest_sum_dbl_for_, 1},
    {"_cpp4rtest_sum_dbl_sexp_for_", (DL_FUNC) &_cpp4rtest_sum_dbl_sexp_for_, 1},
    {"_cpp4rtest_sum_dbl_sexp_writable_for_", (DL_FUNC) &_cpp4rtest_sum_dbl_sexp_writable_for_, 1},
    {"_cpp4rtest_sum_dbl_foreach_", (DL_FUNC) &_cpp4rtest_sum_dbl_foreach_, 1},
    {"_cpp4rtest_sum_dbl_sexp_foreach_", (DL_FUNC) &_cpp4rtest_sum_dbl_sexp_foreach_, 1},
    {"_cpp4rtest_sum_dbl_accumulate_", (DL_FUNC) &_cpp4rtest_sum_dbl_accumulate_, 1},
    {"_cpp4rtest_sum_dbl_sexp_accumulate_", (DL_FUNC) &_cpp4rtest_sum_dbl_sexp_accumulate_, 1},
    {"_cpp4rtest_sum_cplx_r_complex_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_r_complex_out_, 1},
    {"_cpp4rtest_sum_cplx_complexes_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_complexes_out_, 1},
    {"_cpp4rtest_sum_cplx_typed_std_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_typed_std_out_, 1},
    {"_cpp4rtest_sum_cplx_sexp_std_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_sexp_std_out_, 1},
    {"_cpp4rtest_sum_cplx_sexp_sexp_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_sexp_sexp_out_, 1},
    {"_cpp4rtest_sum_cplx_sexp_complexes_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_sexp_complexes_out_, 1},
    {"_cpp4rtest_sum_cplx_foreach_", (DL_FUNC) &_cpp4rtest_sum_cplx_foreach_, 1},
    {"_cpp4rtest_sum_cplx_accumulate_", (DL_FUNC) &_cpp4rtest_sum_cplx_accumulate_, 1},
    {"_cpp4rtest_sum_cplx_sexp_protect_std_out_", (DL_FUNC) &_cpp4rtest_sum_cplx_sexp_protect_std_out_, 1},
    {"_cpp4rtest_sum_int_for_", (DL_FUNC) &_cpp4rtest_sum_int_for_, 1},
    {"_cpp4rtest_sum_int_sexp_for_", (DL_FUNC) &_cpp4rtest_sum_int_sexp_for_, 1},
    {"_cpp4rtest_sum_int_foreach_", (DL_FUNC) &_cpp4rtest_sum_int_foreach_, 1},
    {"_cpp4rtest_sum_int_accumulate_", (DL_FUNC) &_cpp4rtest_sum_int_accumulate_, 1},
    {"_cpp4rtest_add_int_vec_", (DL_FUNC) &_cpp4rtest_add_int_vec_, 2},
    {"_cpp4rtest_as_integers_", (DL_FUNC) &_cpp4rtest_as_integers_, 1},
    {"_cpp4rtest_negate_logical_", (DL_FUNC) &_cpp4rtest_negate_logical_, 1},
    {"_cpp4rtest_logical_to_int_", (DL_FUNC) &_cpp4rtest_logical_to_int_, 1},
    {"_cpp4rtest_logical_to_dbl_", (DL_FUNC) &_cpp4rtest_logical_to_dbl_, 1},
    {"_cpp4rtest_iterator_sum_", (DL_FUNC) &_cpp4rtest_iterator_sum_, 1},
    {"_cpp4rtest_iterator_sum_int_", (DL_FUNC) &_cpp4rtest_iterator_sum_int_, 1},
    {"_cpp4rtest_iterator_find_", (DL_FUNC) &_cpp4rtest_iterator_find_, 2},
    {"_cpp4rtest_iterator_count_", (DL_FUNC) &_cpp4rtest_iterator_count_, 2},
    {"_cpp4rtest_iterator_min_", (DL_FUNC) &_cpp4rtest_iterator_min_, 1},
    {"_cpp4rtest_iterator_max_", (DL_FUNC) &_cpp4rtest_iterator_max_, 1},
    {"_cpp4rtest_iterator_double_values_", (DL_FUNC) &_cpp4rtest_iterator_double_values_, 1},
    {"_cpp4rtest_reverse_vector_", (DL_FUNC) &_cpp4rtest_reverse_vector_, 1},
    {"_cpp4rtest_iterator_at_", (DL_FUNC) &_cpp4rtest_iterator_at_, 2},
    {"_cpp4rtest_iterator_distance_", (DL_FUNC) &_cpp4rtest_iterator_distance_, 1},
    {"_cpp4rtest_raw_copy_", (DL_FUNC) &_cpp4rtest_raw_copy_, 1},
    {"_cpp4rtest_raw_xor_", (DL_FUNC) &_cpp4rtest_raw_xor_, 2},
    {"_cpp4rtest_push_and_truncate_", (DL_FUNC) &_cpp4rtest_push_and_truncate_, 1},
    {"_cpp4rtest_weak_ref_make_alive_", (DL_FUNC) &_cpp4rtest_weak_ref_make_alive_, 2},
    {"_cpp4rtest_weak_ref_value_", (DL_FUNC) &_cpp4rtest_weak_ref_value_, 2},
    {"_cpp4rtest_weak_ref_typeof_", (DL_FUNC) &_cpp4rtest_weak_ref_typeof_, 2},
    {"_cpp4rtest_weak_ref_nil_not_alive_", (DL_FUNC) &_cpp4rtest_weak_ref_nil_not_alive_, 0},
    {"_cpp4rtest_weak_ref_rejects_vec_", (DL_FUNC) &_cpp4rtest_weak_ref_rejects_vec_, 0},
    {NULL, NULL, 0}
};
}
extern "C" attribute_visible void R_init_cpp4rtest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
