# Generated by cpp4r: do not edit by hand

#' @title Is Any Element in a Logical Vector "TRUE"
#' @description Loop over a vector and returns "true" when a "true" element is found in the sequence.
#' @param x logical vector.
#' @export
any_cpp <- function(x) {
	.Call(`_cpp4rvignettes_any_cpp`, x)
}

#' @title Which Elements in a Logical Vector are "TRUE"
#' @description Loop over a vector and returns the positions that are "true". Returns a vector of
#'   integers.
#' @param x logical vector.
#' @export
which_cpp <- function(x) {
	.Call(`_cpp4rvignettes_which_cpp`, x)
}

#' @title Are all Elements in a Vector "TRUE"? (Form 1)
#' @description Loop over a vector and returns "true" if all the elements are "true".
#' @param x logical vector.
#' @export
all_cpp_1 <- function(x) {
	.Call(`_cpp4rvignettes_all_cpp_1`, x)
}

#' @title Are all Elements in a Vector "TRUE"? (Form 2)
#' @description Loop over a vector and returns "true" if all the elements are "true".
#' @param x logical vector.
#' @export
all_cpp_2 <- function(x) {
	.Call(`_cpp4rvignettes_all_cpp_2`, x)
}

#' @title Are all Elements in a Vector "TRUE"? (Form 3)
#' @description Loop over a vector and returns "true" if all the elements are "true".
#' @param x logical vector.
#' @export
all_cpp_3 <- function(x) {
	.Call(`_cpp4rvignettes_all_cpp_3`, x)
}

#' @title Are all Elements in a Vector "TRUE"? (Form 4)
#' @description Loop over a vector and returns "true" if all the elements are "true".
#' @param x logical vector.
#' @export
all_cpp_4 <- function(x) {
	.Call(`_cpp4rvignettes_all_cpp_4`, x)
}

#' @title Cumulative Sum
#' @description Returns a vector of doubles containing the cumulative sum of a vector of doubles.
#' @param x doubles (numeric) vector.
#' @export
cumsum_cpp <- function(x) {
	.Call(`_cpp4rvignettes_cumsum_cpp`, x)
}

#' @title Cumulative Product
#' @description Returns a vector of doubles containing the cumulative product of a vector of doubles.
#' @param x doubles (numeric) vector.
#' @export
cumprod_cpp <- function(x) {
	.Call(`_cpp4rvignettes_cumprod_cpp`, x)
}

#' @title Cumulative Product
#' @description Returns a vector of doubles containing the minimum and maximum of a vector of doubles.
#' @param x doubles (numeric) vector.
#' @export
range_cpp <- function(x) {
	.Call(`_cpp4rvignettes_range_cpp`, x)
}
