# Generated by cpp4r: do not edit by hand

#' @title Plus 1 (C++)
#' @param x integer
#' @description It adds 1 to an integer value.
#' @export
#' @examples plus_one(1)
plus_one <- function(x) {
	.Call(`_cpp4rvendor_plus_one`, x)
}

#' @title Plus 2.0 (C++)
#' @param x double
#' @description It adds 2.0 to a double value.
#' @export
#' @examples plus_two(1.0)
plus_two <- function(x) {
	.Call(`_cpp4rvendor_plus_two`, x)
}
