// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// 05-logical-functions.h
bool any_cpp(logicals x);
extern "C" SEXP _cpp4rvignettes_any_cpp(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(any_cpp(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 05-logical-functions.h
integers which_cpp(logicals x);
extern "C" SEXP _cpp4rvignettes_which_cpp(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(which_cpp(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 05-logical-functions.h
bool all_cpp_1(logicals x);
extern "C" SEXP _cpp4rvignettes_all_cpp_1(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(all_cpp_1(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 05-logical-functions.h
bool all_cpp_2(logicals x);
extern "C" SEXP _cpp4rvignettes_all_cpp_2(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(all_cpp_2(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 05-logical-functions.h
bool all_cpp_3(logicals x);
extern "C" SEXP _cpp4rvignettes_all_cpp_3(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(all_cpp_3(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 05-logical-functions.h
bool all_cpp_4(logicals x);
extern "C" SEXP _cpp4rvignettes_all_cpp_4(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(all_cpp_4(cpp4r::as_cpp<cpp4r::decay_t<logicals>>(x)));
  END_CPP4R
}
// 06-rolling-functions.h
doubles cumsum_cpp(doubles x);
extern "C" SEXP _cpp4rvignettes_cumsum_cpp(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cumsum_cpp(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// 06-rolling-functions.h
doubles cumprod_cpp(doubles x);
extern "C" SEXP _cpp4rvignettes_cumprod_cpp(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(cumprod_cpp(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// 06-rolling-functions.h
doubles range_cpp(doubles x);
extern "C" SEXP _cpp4rvignettes_range_cpp(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(range_cpp(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp4rvignettes_any_cpp", (DL_FUNC) &_cpp4rvignettes_any_cpp, 1},
    {"_cpp4rvignettes_which_cpp", (DL_FUNC) &_cpp4rvignettes_which_cpp, 1},
    {"_cpp4rvignettes_all_cpp_1", (DL_FUNC) &_cpp4rvignettes_all_cpp_1, 1},
    {"_cpp4rvignettes_all_cpp_2", (DL_FUNC) &_cpp4rvignettes_all_cpp_2, 1},
    {"_cpp4rvignettes_all_cpp_3", (DL_FUNC) &_cpp4rvignettes_all_cpp_3, 1},
    {"_cpp4rvignettes_all_cpp_4", (DL_FUNC) &_cpp4rvignettes_all_cpp_4, 1},
    {"_cpp4rvignettes_cumsum_cpp", (DL_FUNC) &_cpp4rvignettes_cumsum_cpp, 1},
    {"_cpp4rvignettes_cumprod_cpp", (DL_FUNC) &_cpp4rvignettes_cumprod_cpp, 1},
    {"_cpp4rvignettes_range_cpp", (DL_FUNC) &_cpp4rvignettes_range_cpp, 1},
    {NULL, NULL, 0}
};
}
extern "C" attribute_visible void R_init_cpp4rvignettes(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
