// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void cpp4r_simplex_phase2_(doubles c, doubles b, doubles_matrix<> A);
extern "C" SEXP _cpp4rsimplexphase2_cpp4r_simplex_phase2_(SEXP c, SEXP b, SEXP A) {
  BEGIN_CPP4R
    cpp4r_simplex_phase2_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(c), cpp4r::as_cpp<cpp4r::decay_t<doubles>>(b), cpp4r::as_cpp<cpp4r::decay_t<doubles_matrix<>>>(A));
    return R_NilValue;
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp4rsimplexphase2_cpp4r_simplex_phase2_", (DL_FUNC) &_cpp4rsimplexphase2_cpp4r_simplex_phase2_, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp4rsimplexphase2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
