// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
list squared_unnamed_(doubles x);
extern "C" SEXP _cpp4romp_squared_unnamed_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(squared_unnamed_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}
// code.cpp
list squared_named_(doubles x);
extern "C" SEXP _cpp4romp_squared_named_(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(squared_named_(cpp4r::as_cpp<cpp4r::decay_t<doubles>>(x)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp4romp_squared_named_",   (DL_FUNC) &_cpp4romp_squared_named_,   1},
    {"_cpp4romp_squared_unnamed_", (DL_FUNC) &_cpp4romp_squared_unnamed_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp4romp(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
