# Generated by cpp4r: do not edit by hand

invert_matrix_ <- function(A) {
  .Call(`_cpp4rgaussjordan_invert_matrix_`, A)
}

solve_system_ <- function(A, b) {
  .Call(`_cpp4rgaussjordan_solve_system_`, A, b)
}
