// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp4r_naive_ols.cpp
doubles_matrix<> naive_ols_(doubles_matrix<> X, doubles_matrix<> Y);
extern "C" SEXP _cpp4rols_naive_ols_(SEXP X, SEXP Y) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(naive_ols_(cpp4r::as_cpp<cpp4r::decay_t<doubles_matrix<>>>(X), cpp4r::as_cpp<cpp4r::decay_t<doubles_matrix<>>>(Y)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp4rols_naive_ols_", (DL_FUNC) &_cpp4rols_naive_ols_, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp4rols(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
